### ISSUE TITLE
Load testing OCaml.org infrastructure

### ISSUE THREAD

**Issue by sabine** [ocaml/infrastructure#161]
As far as I understand:

1. We currently have no idea how many requests per second OCaml.org can handle, especially on pages whose implementation is far from efficient.
2. There's no caching layer, so every request goes straight to the OCaml.org webserver within the Docker container used to deploy it.

For the case that we have a sudden influx of people trying to view OCaml.org at the same time (e.g. Hacker News post blows up, streamers host events with many viewers and a link gets posted in chat), we need to ensure that they can view OCaml.org without the servers going down or becoming unreachable.

A first step to understand where we are at, and what measures are sensible, running a load test on different parts of OCaml.org (especially: package documentation, since we estimate that this is the least efficient part of it) would be super helpful.

We'd like to be able to support at least 10.000 legitimate page views within a minute on the same page, for any page on OCaml.org, by  Nov 15 (which, as I understand, is a pretty tight deadline). We should also assume that a part of these people will navigate to other pages from there.

There's also a realistic possibility that someone would try and run a DDoS attack, and I think we are not equipped for anything like this at the moment either.

**Comment by shonfeder** [comment]
The plan for tackling this over the next week, thanks to guidance from @mtelvers:

- [ ] set up prometheus on the ocaml.org server
  - this will give us metrics in Grafan so we can evaluate the results of load testing
- [ ] instrument load testing
  - [ ] @sabine will provide endpoints and payloads needing particular attention
  - [ ] run tests so we can record the metrics via grafana
- [ ] configuring an http cache via the caddy proxy (https://github.com/caddyserver/cache-handler)
  - see how this affects the load testing metrics, if it enables us to handle our load, we are done

After this course, if we still haven't achieved our needed capacity, we can consider

- using docker swarm to take advantage of more cores by running more server instances on the same machine
- switch to a beefier machine for the server
- explore running on multiple machines
- be on the lookout for perf issues in the source code itself

**Comment by sabine** [comment]
I think a minimal list of endpoints to test would be this:

```
/
/install
/p/core/latest/doc/index.html
/docs/tour-of-ocaml

# all of the top level pages
/docs
/platform
/packages
/community
/changelog
/play

/industrial-users
/academic-users

# some package searches with different query strings
/packages/autocomplete?q=a
/packages/search?q=a
```

At least that's the pages where it would be bad if they break down.

For comprehensive testing, it's best to go through https://github.com/ocaml/ocaml.org/blob/main/src/global/url.ml so that everything's covered, but I think a minimal effort focusing on the actually really important pages here is best, considering the timeframe.

**Comment by shonfeder** [comment]
I have an initial load testing harness I'm experimenting with. Here's a report from simulating up to 1000 concurrent users for 2 mins:

![2024-11-08-222146_1859x1925_scrot](https://github.com/user-attachments/assets/3824fdcc-2af1-4342-8f78-f78607e10bee)

We start hitting very slow response times for even the 50th percentile of visits after just a few seconds of 1000 user load: up to 43 seconds to load a page.

We also managed to get a 4% error rate with this quite light load. We could more intensive tests, but this already shows us that cannot handle nearly the 10,000 concurrent users we are aiming for. Note that we didn't really put a lot of stress on the machines according to our prometheous metrics.

Next step will be trying to drop the http cache into caddy, and see how much this improves things. I'll record a benchmark for a test on staging first, so we try the cache there initially.

**Comment by shonfeder** [comment]
Hitting staging with 10,000 users for about 2 mins was able to produce response times nearing 80 seconds, a 70% failure rate, and maxed at under 230 requests per second:

![2024-11-08-223229_3118x2042_scrot](https://github.com/user-attachments/assets/bcc04f4b-6126-4ea8-bb96-b49544c640f7)

**Comment by shonfeder** [comment]
Running these tests just on my work machine currently, and it should be noted that this places a constraint on how much load I can apply due to my own system resources. However, I used the same approach on a simple site built on ocisgen (running on a pretty tiny VPS) and was able to clock 4k users  with a comparatively fast response time, serving around 1k requests per second with a 0% failure rate, so I am able to but enough pressure on a system to exceed our current limits.

**Comment by shonfeder** [comment]
@sabine Here is the full report of a load test run that ramped up to 10000 users adding 20 users per second:

[running-up-to-10k-users.pdf](https://github.com/user-attachments/files/17696273/running-up-to-10k-users.pdf)

With you knowledge of the server internals, perhaps you will find the response times and error rates for specific action items actionable.

I have been investigating use of caching at the level of the caddy proxy, but I think this is a non-starter since we default all traffic to HTTPS, and the caddy cache only works for http. I will discuss with Mark tomorrow to confirm, in which case we will either need to look to scaling and load balancing, and any improvements the ocaml.org devs can make in poor perf over the next few days.

**Comment by mtelvers** [comment]
Caddy is the HTTPS endpoint.  The reverse proxy requests are over HTTP, which is the part we want to cache.

e.g.

```
{
        cache
}

www.ocaml.org {
        cache
        reverse_proxy www:8080
}
```

**Comment by shonfeder** [comment]
Ah, ok! This is good news. I'll get that configured today then. (I set up caddy with the caching module on a toy server over the weekend. Seems straight forward.)

**Comment by shonfeder** [comment]
On staging with 

- 10000 peak concurrency
- 50 users started/seconds

Before adding the cache:

![2024-11-11-134650_1856x1917_scrot](https://github.com/user-attachments/assets/9ba55ccd-b746-41ec-aaa6-fd1baeaf71b9)

After adding the cache (in https://github.com/mtelvers/ansible/pull/34):

![2024-11-11-151137_1865x1934_scrot](https://github.com/user-attachments/assets/4ace58db-a1be-4c4f-99ad-b4076c077d50)

Key takeaways:

- The error rate dropped from 30% to 0%
- Max RPS went from < 120

**Comment by punchagan** [comment]
This is great! Thanks for sharing detailed notes on the progress, @shonfeder !

**Comment by shonfeder** [comment]
## Change in load testing strategy

I experimented with using more processes in locust, and was not able to put significantly more pressure on the staging server. So I set up a load testing with k6, which seems more performant (it is written in Go vs. locust's python) and more correct (locust was encountering a number of internal errors). The configurations for both the multiprocess locust runs and for k6 are in https://github.com/ocaml/ocaml.org/pull/2810/commits/5d6083d9ddb2693e0f03c9b415dcc2efb0a8cd84

## Disappointing results

I just ran what I thought would be a modest stress test using k6: 1000 users for 1 minute, but the results were pretty dismal and it took the staging server offline;

```
     data_received..................: 169 MB 1.9 MB/s
     data_sent......................: 1.3 MB 14 kB/s
     http_req_blocked...............: avg=277.69ms min=228ns    med=291ms    max=6.59s  p(90)=640.27ms p(95)=684.83ms
     http_req_connecting............: avg=65.72ms  min=0s       med=99.71ms  max=2.47s  p(90)=138.4ms  p(95)=152.9ms 
     http_req_duration..............: avg=34.85s   min=844.83ms med=55.45s   max=1m0s   p(90)=1m0s     p(95)=1m0s    
       { expected_response:true }...: avg=9.72s    min=844.83ms med=9.83s    max=55.45s p(90)=15.39s   p(95)=16.68s  
     http_req_failed................: 49.97% 996 out of 1993
     http_req_receiving.............: avg=16.95s   min=0s       med=7.17s    max=59.66s p(90)=59.52s   p(95)=59.59s  
     http_req_sending...............: avg=125.08µs min=30.54µs  med=92.85µs  max=3.89ms p(90)=211.27µs p(95)=279.36µs
     http_req_tls_handshaking.......: avg=166.8ms  min=0s       med=138.98ms max=6.3s   p(90)=371.86ms p(95)=409.84ms
     http_req_waiting...............: avg=17.89s   min=245.88ms med=1.4s     max=1m0s   p(90)=1m0s     p(95)=1m0s    
     http_reqs......................: 1993   22.130624/s
     vus............................: 1000   min=1000        max=1000
     vus_max........................: 1000   min=1000        max=1000
```

![2024-11-12-172701_1877x1734_scrot](https://github.com/user-attachments/assets/ba4afec1-0041-46c8-8539-f5c8c9de3732)

Detailed results (FYI, @sabine, in case you can look at trying to improve the most problematic endpoints): 
[2024-11-12T16:37:51-results.gz](https://github.com/user-attachments/files/17723630/2024-11-12T16.37.51-results.gz)


## Possible memory leak

It also looks to me like we may have a memory leak:

![2024-11-12-172812_1895x1725_scrot](https://github.com/user-attachments/assets/9a65338c-c819-4c4c-bce6-e26f4caeb447)

We were not collecting any metrics on this server prior to 11/06, so I'm not sure how things looked before. The sudden drop in available memory looks like it corresponded with the beginning of stress testing. In any case, it preceded my addition of the cache handler,so I don't think that is (primarily) to blame.

## Next steps

- Today, @mtelvers and I agreed that we should add an extra instance of the server on the same machine, so that we can share the load between more than one CPU. I'll proceed with that.
- `staging.ocaml.org` remains offline, so I will need to see how we can recover access. Possibly contacting Scaleway?
- I think it's possible that my testing parameters where too aggressive to reflect likely load. E.g., I may need to throttle the amount of requests per second and ensure use ramps up gradually. (That said, I ran the same load thru a toy server built with ocsigen, running on a machine with 1gb of RAM, and also using caddy with the cache handler: the toy server was able to give peaks of 450 RPS, only had %0.02 error rate, mostly maintained an avg response time < 30s, and did not get knocked offline -- so I think we are hitting real problems, and not just suffering from a poorly tuned load).

**Comment by shonfeder** [comment]
Over the last two days, we have run dozens of load tests that led us to completely reconfigure the proxy server, caching, and TLS certification. @mtelvers did the heavy lifting in this work and I provided support.

## Load tests and caching improvements

### The server's original capacities

The server in its previous state would begin to max out the CPU in the order of dozens of concurrent users at rates about 8 requests/second. 

### After adding a cache handler to caddy

After we dropped a cache handler into our load tests, we were able to increase the capacity by an order of magnitude, handling about 100 simulated concurrent users with rates above 30 requests/second. However, caddy became our bottleneck at that point and we were still way wide of our target.

### After adding the varnish cache

Mark swapped out the caddy cache handler for varnish, at which point the load testing setup I was using from my local machine (or some intervening network filtering) became the bottleneck. We switched the load testing configuration to a test machine Mark set up, and hit new limits around 500 concurrent (iirc).

### After adding an additional server instance and using hitch for TLS termination

We ended up adding a second instance of the ocaml.org backend, behind hitch for handling TLS and varnish for caching. Load tests with this configuration were able to reach 500 requests/second, at which point we hit the limits of our load testing tooling. An important caveat is that **we can only handle these kinds of loads when we are hitting the cache**: when requests get thru we fall back to roughly the original limitations.

### Blocking some pesky bots

Monitoring the capacity and load on ocaml.org after this configuration has been deployed, we have seen that bots crawling the site can get the server using 30-60% of their CPUs when they index documentation pages. From the perspective of our caching, these bots are acing as worst-case users, hitting pages off the beaten path. To reduce the ambient load on the server from these bots, I have opened https://github.com/ocaml/ocaml.org/pull/2816

### The Upshot

From our tests and analysis to this point, we should be able to serve more than 500 requests/second for reasonable users viewing a common set of pages (e.g., most of the endpoints in https://github.com/ocaml/infrastructure/issues/161#issuecomment-2464948116). This should allow 10k real users to browse popular pages at a (slow pace) of a couple of clicks per minute. If we get a large burst of users fanning out into different parts of the site and missing the cache, then we are likely to overload the backend.

From our testing and analysis to this point, changes to the backend architecture would be needed to addresses these limitations in a reasonable way.

The new configuration is in https://github.com/mtelvers/ansible/pull/36

### Caveat

We have not been able to build up robust, distributed load testing in the time available to us. We know there are some limitation to the accuracy and intensity of our tests as a result.

## (D)DOS Protections

I have opened https://github.com/mtelvers/ansible/pull/37 to add rate limiting to protect against DOS attacks.

Scaleway offers DDOS protections for all "Dedibox" servers: https://www.scaleway.com/en/docs/dedibox-network/network/reference-content/anti-ddos/  I do not have information on our scaleway accounts, so I don't know how to confirm that we have this protection in place however.
