### ISSUE TITLE
Sandmark nightlies aren't running

### ISSUE THREAD

**Issue by dra27** [ocaml/infrastructure#71]
The Sandmark Nightly service doesn't appear to have pushed any results since 17 August - https://sandmark.tarides.com/status is showing failures across the board.

**Comment by punchagan** [comment]
It seems to have been due to a new version constraint added to `lwt` on August 17 and a new `lwt` version being released. Somehow build failure notifications were missed by the `sandmark-dev` team, probably because of the noise caused by #68 & #70. I'm looking into fixing this.  Thanks @dra27 for noticing and reporting this! :pray:

**Comment by punchagan** [comment]
I've pushed a change, that should restore the nightlies. We can wait for the nightly run tonight, and then close this issue.

**Comment by punchagan** [comment]
The nightlies have successfully run on Navajo. This issue can be closed now.

**Comment by dra27** [comment]
Thank you!
