### ISSUE TITLE
watch.ocaml.org is down

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/infrastructure#89]
Could it be related to github being down?

<img width="375" alt="Screenshot 2024-01-09 at 13 46 10" src="https://github.com/ocaml/infrastructure/assets/2611789/4c8252ef-3fdf-4757-b0cd-67aeb9022fe0">

**Comment by mtelvers** [comment]
The service has been restored

**Comment by mtelvers** [comment]
A massive log file (44GB!) in the Docker overlay2 folder caused the server to run out of space.

**Comment by avsm** [comment]
That's a new one -- what was the logfile?

**Comment by mtelvers** [comment]
`/var/log/nginx/peertube.error.log` within the overlay2 folder.  It looked like, over a period of a week, there were continuous attempts to download a file which didn't exist.  However, the log wasn't increasing when I looked at it.  However, on revisiting it now to check the exact file name, I see that the entries are back.  The source IP is 147.28.133.131, which is amok.recoil.org.  Perhaps there is a federation between these two?  At the moment, there are about 50 lines per second like this:

```
2024/01/09 18:31:02 [error] 14#14: *13191 open() "/var/www/peertube/storage/web-videos/e463f10c-d052-42db-b972-d19bbcaa205d-360.mp4" failed (2: No such file or directory), client: 147.28.133.131, server: watch.ocaml.org, request: "GET /static/webseed/e463f10c-d052-42db-b972-d19bbcaa205d-360.mp4 HTTP/1.1", host: "watch.ocaml.org"
```

I've set iptables to drop these connections until we can get to the bottom of it. [Remove with `iptables -D DOCKER-INGRESS -s 147.28.133.131 -j DROP`.]

**Comment by avsm** [comment]
@mtelvers I think part of the root cause for this might be an missing part of the upgrade. The "assets" volume needs to be deleted on upgrade so that it can be recreated with the latest frontend files, which then form part of the federation API.

See e.g. https://github.com/Chocobozzz/PeerTube/issues/5030 -- this also goes wrong when trying to update the admin config on watch.ocaml.org at the moment (see screenshot)

<img width="966" alt="image" src="https://github.com/ocaml/infrastructure/assets/53164/6dbddcaa-6500-4151-9197-b927ea37dae3">

**Comment by mtelvers** [comment]
@avsm I have deleted the `peertube-assets` volume and restarted the service.  The content has been repopulated.  I don't have access to the admin dashboard so I can't verify whether this has fixed your issue.  However, I've removed the `iptables` rule and the log file is quiet.

**Comment by shonfeder** [comment]
Sounds like this is resolved, and we can reopen if further problems arise.
