### ISSUE TITLE
Server certificates expiring SOON

### ISSUE THREAD

**Issue by AltGr** [ocaml/infrastructure#9]
What are the plans for server certificates ? Has auto-renewal been put in place somewhere ?

I just got notification from Letsencrypt about the expiration of the `opam.ocaml.org` certificate, that I got in a hurry in the middle of ICFP. I am going to renew by hand for now, but:

- the `ocaml.org` certificate is going to expire soon too: who is handling this ?
- are we getting back to a certificate including subdomains, or should I put automated renewal for `opam.ocaml.org` separately ?

**Comment by avsm** [comment]
ocaml.org is currently running lighttpd which is unsupported by certbot ( https://github.com/certbot/certbot/issues/94). I manually renewed it for the moment, but moving forward I'd suggest:

- [ ] switch ocaml.org to using an OCaml webserver (cohttp or http/af depending on @selipou release sched)
- [ ] add support for the certbot path scheme (`/etc/letsencrypt/live/ocaml.org/`) to the server so that autorenew just works. Can use the irmin-watcher portable library for this.
- [ ] in the background, build a letsencrypt API library so we can directly renew via the webserver itself.

For now ocaml.org is fine until Feb 2017

**Comment by avsm** [comment]
This has been resolved.
